### ISSUE TITLE
Issues with detrend='linear' in dft() killing kernel

### ISSUE THREAD

**Issue by paigem** [xgcm/xrft#111]
I have two comments, the first of which is the main issue, while the second is a small, related note. I am currently running the most up-to-date xrft version from GitHub (version 0.2.2+1.g8b7e84e) on Pangeo Cloud.

(1)  I've been trying to use the 'linear' detrend option in `dft()` without success. (I created a sample notebook [here](https://github.com/paigem/pangeo_tests/blob/master/Test_dft_linear_detrend.ipynb) on a subset of CESM data to illustrate this problem, which should be executable on Pangeo Cloud.) Whenever I use the 'linear' option, when using `.load()` to calculate the dft function, the cell runs for awhile (~15 minutes in my notebook example) and eventually kills the kernel without any warning or error messages. This does not seem to be an issue with running the computation with dask gateway, as I have had this problem running both with and without dask (and when trying to use dask gateway, the dashboard showed no activity the whole time). When running with `detrend='constant'` or `detrend=None` I don't have any errors and the function runs in under 10 seconds. I've looked at the xrft code a bit and it may have to do with the dask chunking, but I'm not sure at this point. I believe @navidcy has had similar problems.

~(2) I just noticed today that I've been running the dft() function with `detrend=True`. This ran just fine, but also didn't raise any errors saying that 'True' is, in fact, not one of the options. I wonder if it makes sense to add a warning that any arguments that are not either 'constant' or 'linear' will be treated as 'None'? (I realize that this was entirely my mistake in not reading the xrft docs better, but since the 'window' flag does use 'True' it may be confusing for others as well.)~ (This comment is now in issue #114.)

I would be happy to make a pull request for these issues if we see the need, but since I'm new to this community I might need a few tips from the more experienced developers out there!

**Comment by roxyboy** [comment]
Thanks for raising the issue. Upon looking at your example, it seems that you don't chunk your data in the lat/lon direction when taking the FFT. Could you try the `linear` option with smaller chunks and see if that works? I might be a memory issue.

As for your second point, I agree and raising a warning is probably a good idea.

**Comment by rabernat** [comment]
Worth noting here that, since we implemented detrending, xarray has added support for [polyfit](http://xarray.pydata.org/en/latest/generated/xarray.Dataset.polyfit.html), which is totally compatible with dask regardless of chunking. Therefore we should probably replace the internal implementation of detrending with the "official" xarray version.

**Comment by paigem** [comment]
Thanks @roxyboy for your response. I have tried using the `linear` flag with smaller chunks in the lat/lon direction with the same results. I'll note that without chunking in lat/lon the data array is only 16MB, so my understanding is that chunking more shouldn't be necessary with such a small data subset. 

Looking a bit more at the code, it looks like the `xrft.py` function creates chunks of size 1 for all dimensions that are not being detrended. I don't understand why this is necessary, and I'm wondering if this might be causing some of the trouble? This chunking takes place on line 381 of `xrft.py`:

![Screen Shot 2020-10-02 at 12 18 12](https://user-images.githubusercontent.com/26591824/94882116-72171980-04aa-11eb-94ec-3a02257a7da1.png)


The result of the above lines can be seen in the screenshot below where the output from my dft() function results in a DataArray of size (400,500,11) with chunks of size (1,1,11).

Original DataArray before dft() function is applied:
![Screen Shot 2020-10-02 at 12 12 49](https://user-images.githubusercontent.com/26591824/94881917-f4eba480-04a9-11eb-9ab0-cc4e2177f1b6.png)

DataArray after dft() function is applied:
![Screen Shot 2020-10-02 at 12 13 13](https://user-images.githubusercontent.com/26591824/94881954-046aed80-04aa-11eb-9478-3a492ea633d5.png)

I may well be off-the-mark here, but I did a quick test of applying the `spicy.signal.detrend()` function directly to the time dimension of my DataArray . With no chunks (as in the original DataArray shown above), the function runs in under 5 seconds. With lat/lon chunks of size 1, it ran successfully but took 17 minutes. (All of this was run without dask gateway.)

Or maybe using xarray's `polyfit()`, as @rabernat suggested, would solve this problem? Thanks for your help with this!

**Comment by navidcy** [comment]
+1 here: I tried chunking spatial dimensions but problem persisted...

**Comment by roxyboy** [comment]
Ok, well in that case, instead of putting in the effort to try to make the `detrend` function work, I suggest we move on with implementing `polyfit`.

**Comment by navidcy** [comment]
@roxyboy, I guess the idea is to use `xarray.polyfit` to find the linear tread and then subtract it from the data, right?

@paigem should we try to have a go at it and make a PR?

**Comment by rabernat** [comment]
We would be very happy to walk you through the PR process.

**Comment by paigem** [comment]
Yes, let's make a PR, @navidcy!
